import graphviz
flowchart = graphviz.Digraph('flowchart')
flowchart.node('1','ARE YOU USING THE LATEST VERSION OF THE PLUGIN X',shape='diamond')
flowchart.node('2','DEACTIVATE ALL PLUGINS EXCEPT X',shape='box')
flowchart.node('3','UPDATE TO THE LATEST VERSION OF PLUGIN X',shape='box')
flowchart.node('4','IS THE PROBLEM STILL THERE',shape='diamond')
flowchart.node('5','IS THE PROBLEM STILL THERE',shape='diamond')
flowchart.node('6','SWITCH TO THE DEFAULT THEME',shape='box')
flowchart.node('7','IS THE PROBLEM STILL THERE',shape='diamond')
flowchart.node('8','IT IS A BUG IN THE PLUGIN X',shape='oval')
flowchart.node('9','IT IS A CONFLICT WITH YOUR THEME',shape='oval')
flowchart.node('10','ACTIVATE ONE OF THE PREVIOUSLY DEACTIVATED PLUGINS',shape='box')
flowchart.node('11','IS THE PROBLEM BACK',shape='diamond')
flowchart.node('12','IT IS A CONFLICT WITH THE PLUGIN YOU LAST ACTIVATED',shape='oval')
flowchart.edge('1','2','YES')
flowchart.edge('1','3','NO')
flowchart.edge('3','4','')
flowchart.edge('4','2','YES')
flowchart.edge('2','5','')
flowchart.edge('5','6','YES')
flowchart.edge('6','7','')
flowchart.edge('7','8','YES')
flowchart.edge('5','10','NO')
flowchart.edge('10','11','')
flowchart.edge('11','12','YES')
flowchart.edge('11','10','NO')
flowchart.edge('7','9','NO')
flowchart.render(view=True, format='png', outfile='Flowchart/flowchart.png', cleanup=True)
print('flowchart.png generated correctly!')
